<?php

namespace Phpbr\Bundle\AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ArtigoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArtigoRepository extends EntityRepository
{

    /**
     * @param $params
     *
     * @return array|null
     */
    public function paramConverterPorSlug($params) {
        $result = null;

        if (!empty($params) && isset($params['slug'])) {
            $query = $this->createQueryBuilder('Artigo')
                ->where('Artigo.publicado = :flagPublicado')
                ->andWhere('Artigo.slug = :slug')
                ->setParameters(array(
                    'flagPublicado' => true,
                    'slug' => $params['slug']
                ));

            $result = $query->getQuery()->getOneOrNullResult();
        }

        return $result;
    }

    /**
     * @param null $qte
     *
     * @return array
     */
    public function listaArtigosAtivos($qte = null) {
        $query = $this->createQueryBuilder('Artigo')
            ->where('Artigo.publicado = :flagPublicado')
            ->orderBy('Artigo.score', 'DESC')
            ->addOrderBy('Artigo.dataPublicado', 'DESC')
            ->setParameter('flagPublicado', true);

        if (is_numeric($qte)) $query->setMaxResults($qte);

        $query = $query->getQuery();

        return $query->getResult();
    }
}
