<?php

namespace Phpbr\Bundle\AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Pagerfanta\Adapter\DoctrineORMAdapter;

/**
 * ColeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ColeRepository extends EntityRepository
{
    /**
     * Retorna Adapter para pagerfanta (paginacao)
     *
     * @return DoctrineORMAdapter
     */
    public function listaColesAdapter() {
        $query = $this->createQueryBuilder('Cole')
            ->orderBy('Cole.id', 'DESC');
        $pagerfantaAdapter = new DoctrineORMAdapter($query);
        return $pagerfantaAdapter;
    }

}
