<?php

namespace Phpbr\Bundle\AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Pagerfanta\Adapter\DoctrineORMAdapter;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends EntityRepository
{

    /**
     * @param null $qte
     *
     * @return array
     */
    public function listRecentEvents($qte = null) {

        $query = $this->createQueryBuilder('Event')
            ->where('Event.approved_at not :null')
            ->orderBy('Event.created_at', 'DESC')
            ->setParameters(array(
                'null' => null
            ));

        if (is_numeric($qte)) $query->setMaxResults($qte);

        $query = $query->getQuery();

        return $query->getResult();
    }

    /**
     * Retorna Adapter para pagerfanta (paginacao)
     *
     * @return DoctrineORMAdapter
     */
    public function listActiveEventsAdapter() {

        $query = $this->createQueryBuilder('Event')
            ->where('Event.approved_at not :flagPublicado')
            ->andWhere('Event.approved_at = :aprovado')
            ->orderBy('Event.created_at', 'DESC')
            ->setParameters(array(
                'flagPublicado' => null
            ));

        $pagerfantaAdapter = new DoctrineORMAdapter($query);

        return $pagerfantaAdapter;
    }

    /**
     * @param $usuario
     *
     * @return DoctrineORMAdapter
     */
    public function listUsersEvents($user) {

        $query = $this->createQueryBuilder('Event')
            ->where('Event.user = :user')
            ->orderBy('Event.created_at', 'DESC')
            ->setParameter('user', $user);

        $pagerfantaAdapter = new DoctrineORMAdapter($query);

        return $pagerfantaAdapter;
    }

    /**
     * List all events
     * @return array
     */
    public function listaAdminArtigos() {

        $query = $this->createQueryBuilder('Artigo')
            ->andWhere('Artigo.publicado = true')
            ->orderBy('Artigo.dataPublicado', 'ASC');

        return $query->getQuery()->getResult();
    }

}

