<?php

namespace Phpbr\AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Pagerfanta\Adapter\DoctrineORMAdapter;

/**
 * ColeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ColeRepository extends EntityRepository
{
    /**
     * Retorna Adapter para pagerfanta (paginacao)
     *
     * @return DoctrineORMAdapter
     */
    public function listaColesAdapter() {
        $query = $this->createQueryBuilder('Cole')
            ->orderBy('Cole.id', 'DESC');
        $pagerfantaAdapter = new DoctrineORMAdapter($query);
        return $pagerfantaAdapter;
    }

    /**
     * @param int $qte
     *
     * @return array
     */
    public function listaColes($qte = 10) {
        $query = $this->createQueryBuilder('Cole')
            ->orderBy('Cole.dataCriacao', 'DESC');

        if (is_numeric($qte)) $query->setMaxResults($qte);

        return $query->getQuery()->getResult();
    }

}
