<?php

namespace Phpbr\AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Pagerfanta\Adapter\DoctrineORMAdapter;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends EntityRepository
{

    /**
     * @param null $qte
     *
     * @return array
     */
    public function listRecentEvents($qte = null) {

        $query = $this->createQueryBuilder('Event')
            ->where('Event.approved_at not :null')
            ->orderBy('Event.created_at', 'DESC')
            ->setParameters(array(
                'null' => null
            ));

        if (is_numeric($qte)) $query->setMaxResults($qte);

        $query = $query->getQuery();

        return $query->getResult();
    }

    /**
     * Retorna Adapter para pagerfanta (paginacao)
     *
     * @return DoctrineORMAdapter
     */
    public function listActiveEventsAdapter() {

        $query = $this->createQueryBuilder('Event')
            ->where('Event.approved_at not :flagPublished')
            ->andWhere('Event.approved_at = :approved')
            ->orderBy('Event.created_at', 'DESC')
            ->setParameters(array(
                'flagPublished' => null,
                'approved'
            ));

        $pagerfantaAdapter = new DoctrineORMAdapter($query);

        return $pagerfantaAdapter;
    }

    /**
     * List all events
     * @return array
     */
    public function listArticlesAdmin() {

        $query = $this->createQueryBuilder('Article')
            ->andWhere('Article.published = true')
            ->orderBy('Article.publishedAt', 'ASC');

        return $query->getQuery()->getResult();
    }

}

