<?php

namespace Phpbr\AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Pagerfanta\Adapter\DoctrineORMAdapter;

/**
 * PasteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PasteRepository extends EntityRepository
{
    /**
     * Retorna Adapter para pagerfanta (paginacao)
     *
     * @return DoctrineORMAdapter
     */
    public function listPastesAdapter() {
        $query = $this->createQueryBuilder('Paste')
            ->orderBy('Paste.id', 'DESC');

        $pagerfantaAdapter = new DoctrineORMAdapter($query);
        return $pagerfantaAdapter;
    }

    /**
     * @param int $qty
     *
     * @return array
     */
    public function listPastes($qty = 10) {
        $query = $this->createQueryBuilder('Paste')
            ->orderBy('Paste.createdAt', 'DESC');

        if (is_numeric($qty)) $query->setMaxResults($qty);

        return $query->getQuery()->getResult();
    }

}
