<?php

namespace Phpbr\AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    /**
     * @param int $qte
     *
     * @return array
     */
    public function listaUltimosUsuarios($qte = 10) {
        $query = $this->createQueryBuilder('User')
            ->orderBy('User.id', 'DESC');

        if (is_numeric($qte)) $query->setMaxResults($qte);

        return $query->getQuery()->getResult();
    }
}
