<?php

namespace Phpbr\AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    /**
     * @param int $qty
     *
     * @return array
     */
    public function listMostRecentUsers($qty = 10) {
        $query = $this->createQueryBuilder('User')
            ->orderBy('User.id', 'DESC');

        if (is_numeric($qty)) $query->setMaxResults($qty);

        return $query->getQuery()->getResult();
    }
}
